Support subcommad-style invocation, e.g.
zenlog open-last-log

diff --git a/zenlog b/zenlog
--- a/zenlog
+++ b/zenlog
@@ -96,16 +96,15 @@ EOF
   exit 1
 }
 
-# TOOD: Rewrite all in perl.
-# TODO: Add completion helper and find from recent logs.
-
-fullname="$(readlink -f "$0")"
-name="$(basename "$fullname")"
-
 # Optionally get environmental variables from ~/.zenlogrc
 if [[ -f "$HOME/.zenlogrc" ]] ; then
   . "$HOME/.zenlogrc"
 fi
+
+my_full_name="$(readlink -f "$0")"
+my_name="$(basename "$my_full_name")"
+
+. "$my_full_name.bash"
 
 temp=${TEMP:-${TMP:-/tmp}}
 log_dir=${ZENLOG_DIR:-${temp}/zenlog}
@@ -131,14 +130,16 @@ while getopts "fsd:hp:yc:P" opt; do
 done
 shift $(($OPTIND - 1))
 
+# Handle -f.
 if (( $show_free_space )) ; then
   df --output=avail $ZENLOG_DIR/ | sed -e 1d
   exit ${PIPESTATUS[0]}
 fi
 
+# Handle -p.
 if (( $purge_days >= 0 )) ; then
   if ! (( $purge_yes )) ; then
-    echo -n "$name: Purging logs older than $purge_days days? (y/N) "
+    echo -n "$my_name: Purging logs older than $purge_days days? (y/N) "
     read res
     [[ "$res" == "y" || "$res" == "Y" ]] || exit 1
   fi
@@ -159,35 +160,46 @@ if (( $purge_days >= 0 )) ; then
   exit 0
 fi
 
+# Handle -s.
 if (( $shell_helper )) ; then
-  cat "$fullname.bash"
+  cat "$my_full_name.bash"
   exit 0
+fi
+
+# Handle zenlog sub-command
+if (( $# > 0 )) ; then
+  subcommand="$1"
+  shift
+  candidate="zenlog_${subcommand}"
+  for full_command in \
+      "$candidate" \
+      "${candidate//-/_}" \
+      "${candidate//_/-}"; do
+    if type "$full_command" >&/dev/null ; then
+      "$full_command" "$@"
+      exit $?
+    fi
+  done
+  echo "$my_name: Unknown subcommand: $subcommand." 1>&2
+  exit 1
 fi
 
 # Start
 
-if [[ "$ZENLOG_TTY" == $(tty) ]] ; then
-  echo "$name: Error: already in zenlog." 1>&2
+if in_zenlog ; then
+  echo "$my_name: Error: already in zenlog." 1>&2
   exit 1
 fi
 
-export ZENLOG_TEMP_DIR="${temp}"
-export ZENLOG_PID=$$
-
-: ${ZENLOG_ALWAYS_184:=}
-export ZENLOG_ALWAYS_184
-
 export ZENLOG_START_COMMAND
 export ZENLOG_CUR_LOG_DIR=$log_dir
+export ZENLOG_PID=$$
 export ZENLOG_OUTER_TTY=$(tty)
+export ZENLOG_ALWAYS_184
+export ZENLOG_COMMAND_PREFIX # Example: (builtin|time)
 
-# Example: (builtin|time)
-export ZENLOG_COMMAND_PREFIX=${ZENLOG_COMMAND_PREFIX:-}
-
-echo "$name: Logging to $ZENLOG_CUR_LOG_DIR ..."
-
+echo "$my_name: Logging to $ZENLOG_CUR_LOG_DIR ..."
 rm -fr "$ZENLOG_CUR_LOG_DIR/pids/$ZENLOG_PID"
-
 exec script -qf \
     -c 'export ZENLOG_TTY=$(tty); exec $ZENLOG_START_COMMAND' \
-    >( exec "$fullname.pl" )
+    >( exec "$my_full_name.pl" )
